system:
  num_cdus: 2778  #  800,000 Vera Rubin total
  racks_per_cdu: 3
  nodes_per_rack: 72   # 600kW # like NV72
  chassis_per_rack: 1
  nodes_per_blade: 1
  switches_per_chassis: 72  # Chassis concept is Cray => NV72?
  nics_per_node: 1  # Most likely 4
  rectifiers_per_chassis: 1  # power / losses will be set to zero as this is unknown
  nodes_per_rectifier: 1  # power / losses will be set to zero as this is unknown
  #missing_racks:
  down_nodes: []
  cpus_per_node: 1
  gpus_per_node: 4  # Chiplets 4?
  cpu_peak_flops: 2048000000000.0  # Insignificant
  gpu_peak_flops: 15000000000000000000.0  # 15EFlops/s FP4
  cpu_fp_ratio: 0.667
  gpu_fp_ratio: 0.667
power:
  power_gpu_idle:  200 # 200 == 4* 50
  power_gpu_max:  2200  # 2kW  per node = 4*525
  power_cpu_idle: 90
  power_cpu_max: 280
  power_mem: 74.26
  power_nic: 20
  power_nvme: 30
  power_switch: 250
  power_cdu: 8473.47
  power_update_freq: 15
  rectifier_peak_threshold: 13670
  sivoc_loss_constant: 0
  sivoc_efficiency: 1.00
  rectifier_loss_constant: 0
  rectifier_efficiency: 1.00
  power_cost: 0.094
scheduler:
  job_arrival_time: 1
  mtbf: 11
  trace_quanta: 15
  min_wall_time: 3600
  max_wall_time: 43200
  ui_update_freq: 900
  max_nodes_per_job: 9000
  job_end_probs:
    COMPLETED: 0.63
    FAILED: 0.13
    CANCELLED: 0.12
    TIMEOUT: 0.11
    NODE_FAIL: 0.01
uq:
  power_gpu_uncertainty: 0.05
  power_cpu_uncertainty: 0.05
  power_mem_uncertainty: 0.05
  power_nic_uncertainty: 0.05
  power_nvme_uncertainty: 0.05
  power_cdus_uncertainty: 0.05
  power_node_uncertainty: 0.002
  power_switch_uncertainty: 0.05
  rectifier_power_uncertainty: 0.05
